### ISSUE TITLE
Vegas 14 incompatible

### ISSUE THREAD

**Issue by composition-cassidy** [otomad/VegasScripts#1]
Hi, you state that Vegas 14 is compatible with the script but I run into this error. If you could fix that, it would be greatly appreciated. The sparta remix community just noticed your script package here and it's incredible, but most of us use 14 so we would really like it if you fixed this bug. Thank you
<img width="719" alt="Screenshot 2022-05-08 191125" src="https://user-images.githubusercontent.com/99601533/167289524-22ce265e-f032-4ee5-b590-9a7ccf63b57b.png">
!

**Comment by composition-cassidy** [comment]
Hello? Will the issue be fixed? Or is there an easy solution. I would really like to know

**Comment by otomad** [comment]
Oh, sorry for the inconvenience. According to other users' test, we found that the script only works on Vegas pro 16 and above. The reason is that the old version does not support some features that are available in the new version.
For now, you can try the oldest version 4.9.25.0 which without the new features, or wait for subsequent versions to update.

**Comment by otomad** [comment]
The scripts for compatible older versions have been updated but not tested yet. If you have any problems during in using, please reply here.

**Comment by composition-cassidy** [comment]
Tested on Vegas 14, this error still pops up
![170345372-4a1424bf-f742-4628-8380-e6a487e0dd6e](https://user-images.githubusercontent.com/99601533/170352785-e16b9ddd-2db9-4ab5-b148-d10eb2ce75ef.png)

**Comment by otomad** [comment]
Sorry for that. Because I don't have an old version of Vegas, I can't test it. Please try the following files and overwrite the previous ones. Please give me feedback whether the script is executed successfully or not.

https://github.com/otomad/VegasScripts/releases/tag/v4.17.26.0-beta

**Comment by composition-cassidy** [comment]
Still nothing yet, is there any way I can give you the Vegas 14 link I use myself?
<img width="728" alt="image" src="https://user-images.githubusercontent.com/99601533/170368085-84c129ec-0d2b-4581-8203-8f1c9e79e546.png">

**Comment by otomad** [comment]
Sorry, can you give me a file in your vegas directory? Maybe I can use for testing. Thanks.
> C:\Program Files\VEGAS\VEGAS Pro 14.0\ScriptPortal.Vegas.dll

**Comment by otomad** [comment]
I've installed Vegas 15 for testing, and solved some problems. Except for a few new version features that are not available. It should solved this issue.

https://github.com/otomad/VegasScripts/releases/latest

**Comment by composition-cassidy** [comment]
It works!! Thank you so much. Do you have any spots where I can donate to you?

**Comment by otomad** [comment]
You're welcome, no donation required, have fun!
