### ISSUE TITLE
New YTPMV+

### ISSUE THREAD

**Issue by StudiosReklamy** [otomad/VegasScripts#10]
Hi mody let you otomad my turn libytpmv it is called up the new ytpmv+ beta 1 coming your back on soon as the a visually and effect and audio and 3d and on day audio source and modules sources and videos sources and tune github pitched generator and audio and video and chiptune a all more future release feature betas and enjoy

**Comment by StudiosReklamy** [comment]
Coming soon 2022 October 5 New YTPMV+

**Comment by Evauation** [comment]
> Coming soon 2022 October 5 New YTPMV+

You gonna open source it before or after release?
Also, it's kinda weird you're announcing a release of a script/program on an issue on here. ¯\_(ツ)_/¯

**Comment by StudiosReklamy** [comment]
Libytpmv is called a my 2022 September 16 to new ytpmv+ beta release feature program and script and beta's 2022 September 17

**Comment by StudiosReklamy** [comment]
Open sources YTPMV+ old years 2012 2022 October 02 has constantly finished the 2022 open source ytpmv+ beta version released with download.ytpmvprogram.com

**Comment by Evauation** [comment]
Nothing came about, should close!
