### ISSUE TITLE
certain vegas projects will cause the script to error out

### ISSUE THREAD

**Issue by staticanimal** [otomad/VegasScripts#12]
loading some specific video projects will cause the "C:\Program Files\VEGAS\VEGAS Pro 14.0\Script Menu\Otomad Helper.cs : Metadata file 'Microsoft.WindowsAPICodePack.Shell.dll' could not be found" error to pop up every single time i try to load the script. restarting vegas does not fix this as the error only starts showing up every time the project is loaded, making the script entirely impossible to use within that exact project.

**Comment by otomad** [comment]
Hello, please download the lastest release zip file, unzip all files and make sure to OVERWRITE existing files.

NOTE THAT YOU MUST OVERWRITE THE "Otomad Helper.cs.config" FILE.

**Comment by staticanimal** [comment]
just updated. overwrote every single file from both the script download and the datamosh extensions. still errors out in the exact same way.

**Comment by Evauation** [comment]
> just updated. overwrote every single file from both the script download and the datamosh extensions. still errors out in the exact same way.

I don't have this issue anymore but a way to fix it (if either temporary or permanently) is to edit the config file and delete the 2 microsoft dll lines in the file. **Backup the config file** if the script decides to stop working for any other reason.

**Comment by otomad** [comment]
I'm really sorry, I provided the wrong "Otomad Helper.cs.config" file in the last version, please download [the latest version](https://github.com/otomad/OtomadHelper/releases/latest) to replace it.

**Comment by staticanimal** [comment]
that's done the trick, working as intended now.
