### ISSUE TITLE
Script not working on Vegas Pro 20

### ISSUE THREAD

**Issue by spqrtxn** [otomad/VegasScripts#13]
I have Sony Vegas pro 20, but when I try to execute the script, it crashes the entire program. I tried tweaking with MiDi settings in both FL Studio and the script UI.

**Comment by Evauation** [comment]
Download the latest version and replace all the files with the new version files in the script menu folder.

But I have never seen Otomad Helper crash Vegas Pro before...

**Comment by spqrtxn** [comment]
I have the latest version. I just don't know what could be causing it. I think it's just the specific version since it's still brand new.

**Comment by otomad** [comment]
Can you show more details? Such as screenshots or screen recordings, or MIDI files used.

Based on the current information it is not yet possible to infer where the problem is. You said it was a problem with the MIDI settings, so I'm guessing the problem might be related to the MIDI file used.

**Comment by spqrtxn** [comment]
Note that I tried this many times even with different MiDi files and a lot of updating.

https://user-images.githubusercontent.com/117704660/200957909-11c2f22c-4056-4442-b185-6aaa90367da6.mp4

**Comment by otomad** [comment]
Oh my god, I've never seen this before...

Before solving the problem, you can check the following first:

1. Your Vegas minor version. this is my Vegas version. I can't guarantee that Magix modifies a certain API in a later minor update.
![image](https://user-images.githubusercontent.com/56647156/200994878-aa9ef963-f412-4e46-bb01-034ca75c32cf.png)
2. Select *File > Reset user configuation* to restore settings to default.
![image](https://user-images.githubusercontent.com/56647156/200994980-db9680ed-4c5e-4957-9c2c-3d92a97e0571.png)
3. Check to see if your Vegas is **rendering** properly.

If you have Visual Studio installed, you can reply and I'll show you how to debug it.

**Comment by otomad** [comment]
I guess this might be related to the new progress bar dialog introduced.

You could try [v4.20.16.0](https://github.com/otomad/OtomadHelper/releases/tag/v4.20.16.0) if it works.

**Comment by spqrtxn** [comment]
Ok downloading 4.20.16 fixed the issue. 
Thanks lol.

**Comment by otomad** [comment]
A new option has been added to [the latest version](https://github.com/otomad/OtomadHelper/releases/latest) to use the legacy progress dialog.

By selecting the menu *File > Enable legacy progress dialog*.

You could try it if it can prevents the Vegas from crashing.
