### ISSUE TITLE
在Vegas 17下通过 工具--脚本化中选择OtomadHelper时报错

### ISSUE THREAD

**Issue by cdromcdrom** [otomad/VegasScripts#18]
如题，已解压OtomadHelper对应版本至脚本目录下，已安装数据抹失扩展包

Vegas提示：错误：未知异常
详细信息：
System.ArgumentNullException: 值不能为 null。
参数名: v1
   在 System.Version.op_LessThan(Version v1, Version v2)
   在 Otomad.VegasScript.OtomadHelper.V4.ConfigForm..ctor(EntryPoint entryPoint) 位置 c:\Users\Administrator\AppData\Local\Temp\5g1gaqv4\5g1gaqv4.0.cs:行号 26013
   在 Otomad.VegasScript.OtomadHelper.V4.EntryPoint.ShowConfigForm() 位置 c:\Users\Administrator\AppData\Local\Temp\5g1gaqv4\5g1gaqv4.0.cs:行号 285
   在 Otomad.VegasScript.OtomadHelper.V4.EntryPoint.FromVegas(Vegas myVegas) 位置 c:\Users\Administrator\AppData\Local\Temp\5g1gaqv4\5g1gaqv4.0.cs:行号 2674

系统：Windows 10专业版

**Comment by otomad** [comment]
您好。你的Vegas版本号是多少？

**Comment by otomad** [comment]
请尝试使用刚才更新的[最新版](https://github.com/otomad/OtomadHelper/releases/latest)。

如果仍未解决问题，请继续在此处回复。

**Comment by cdromcdrom** [comment]
问题已解决，Vegas 17与Vegas 20下使用最新版本均正常
感谢您的快速修复，在此祝您新年快乐
