### ISSUE TITLE
YTP feature doesnt work

### ISSUE THREAD

**Issue by composition-cassidy** [otomad/VegasScripts#20]
![image](https://user-images.githubusercontent.com/99601533/211907092-131b22ce-bdaf-4960-916c-6267ead18d2a.png)
tried to use it on 1 small clip, and this happened

**Comment by Evauation** [comment]
Can confirm this happens on Vegas Pro 20. Couldn't recreate on Vegas Pro 18 (my current version)

![image](https://user-images.githubusercontent.com/108847709/211908987-87eea3d9-dae8-4eef-ad2d-e635482c7c6f.png)

**Comment by otomad** [comment]
[Fixed](https://github.com/otomad/OtomadHelper/releases/latest)!

**Comment by Evauation** [comment]
> [Fixed](https://github.com/otomad/OtomadHelper/releases/latest)!

nice
