### ISSUE TITLE
Script keeps generating a solid color circle despite the specified event being selected

### ISSUE THREAD

**Issue by EtsGitHubTime** [otomad/VegasScripts#22]
The script generates a white circular outline even if the event to be generated is selected. Moreover, the script does not correctly detect the source event despite the source name being shown on the selected track event setting.
![Screenshot_20230129_093421](https://user-images.githubusercontent.com/100252240/215299215-876b5297-f288-4379-b0d9-b5c0c951c231.png)
![Screenshot_20230129_094208](https://user-images.githubusercontent.com/100252240/215299502-2d401f6e-4135-4701-aff1-67c28521a84a.png)

**Comment by otomad** [comment]
You are using a MIDI track with drum kit, it will automatically generate Cookie Cutter layers as a kind of YTPMV style.

If you don't want to use this style and want to use the source you specified, **please go to the "Sonar" tab, uncheck the "Enable sonar effects for drum kits" check box.**

**Comment by EtsGitHubTime** [comment]
oh i didn't know. thanks for telling me.

**Comment by otomad** [comment]
You can read the [documentation](https://docs.google.com/document/d/1PEkh0_WFDLUAYGD-YzIDNXUQiAKqogEvpuRQhfqz9ng/edit).
