### ISSUE TITLE
Is there a way to use the visual effects on selected tracks?

### ISSUE THREAD

**Issue by jericjan** [otomad/VegasScripts#23]
I noticed that the Video tab only works if you are trying to generate a YTPMV with a midi file. I have a project where I already created the YTPMV but all I need is to add the visual effects like horizontal flips. Is this a feature of the script? If not, can I request it to be added?

**Comment by Evauation** [comment]
Go to Tools, click on Apply PV Visual Effect and then select Horizontal Flip and apply to the select video track events.

**Comment by jericjan** [comment]
Oh, I see. I didn't read the Tools tab in the documentation. My bad. Thanks!
