### ISSUE TITLE
help

### ISSUE THREAD

**Issue by johneggman101** [otomad/VegasScripts#24]
![Screenshot (55)](https://user-images.githubusercontent.com/123841836/216846821-865f2a1f-c4ff-4e30-ac11-d27817db73e5.png)

**Comment by Evauation** [comment]
You're using the Vegas Pro 16+ Version of Otomad Helper on Vegas Pro 15.

This is what you should be using: https://github.com/otomad/OtomadHelper/releases/download/v4.25.12.0/1_otomad_helper_v4.25.12.0_vegas1415.zip

**Comment by Evauation** [comment]
Provided that there was no response. This issue is most likely resolved.
