### ISSUE TITLE
Otomad giving error on opening.

### ISSUE THREAD

**Issue by gvnfc3** [otomad/VegasScripts#28]
![image](https://user-images.githubusercontent.com/60042851/221644907-c608ba84-cbe1-463e-b150-c56a3da1e5b4.png)

**Comment by Evauation** [comment]
Do you have the corresponding version downloaded for Vegas Pro 14?
Is your DLL folder inside the script menu folder and the DLL unblocked, this is what it should look like.
(e.g. Path -> \Script Menu\DLL\NAudio.dll)
![image](https://user-images.githubusercontent.com/108847709/221689107-2b67f35d-f88c-4e09-9294-8adac35f00bd.png)

**Comment by gvnfc3** [comment]
Unblocking the DLL seems to have fixed it.
