### ISSUE TITLE
(Vegas pro 13) May be an odd oversight, though with newer versions of Otomad it shows an Error with HSL Adjust and doesn't register the midi

### ISSUE THREAD

**Issue by lizzieoats** [otomad/VegasScripts#31]
https://user-images.githubusercontent.com/127633540/224514829-7afd92f5-58a2-4b5c-952e-1ccbe871d9c7.mp4

**Comment by otomad** [comment]
May I ask if there is "HSL Adjust" Video FX in your Vegas Pro 13?

**Comment by lizzieoats** [comment]
> May I ask if there is "HSL Adjust" Video FX in your Vegas Pro 13?

it might be a bug on my end, dont worry I got it to work with vegas pro 14 :p

**Comment by otomad** [comment]
[The lastest version](https://github.com/otomad/OtomadHelper/releases/latest) may work in your Vegas Pro 13 now.
