### ISSUE TITLE
Where do i even put everything

### ISSUE THREAD

**Issue by 4stacks67** [otomad/VegasScripts#46]
### Vegas Pro Version

Vegas Pro 20+

### Otomad Helper Version

Latest

### Describe the bug

Idk where to put the whole thing in

**Comment by Evauation** [comment]
what?

**Comment by 4stacks67** [comment]
idk where to put everything
I dont see any folders in the script menu, or dll
and dk where to put the cs file
i'm also using the trial version

**Comment by Evauation** [comment]
Make a folder called Vegas Script Menu in Documents or My Documents
C:\Users\[YOURUSERNAME]\Documents\Vegas Script Menu

Then put all the script files in that folder.

**Comment by Evauation** [comment]
Also you don't download the source code, you download the latest release here and put it in that folder
https://github.com/otomad/OtomadHelper/releases/latest

Download the version that corresponds to your Vegas Pro Version.

**Comment by 4stacks67** [comment]
Thx! I Followed You!
