### ISSUE TITLE
I Can't Fix This

### ISSUE THREAD

**Issue by 4stacks67** [otomad/VegasScripts#47]
### Vegas Pro Version

Vegas Pro 20+

### Otomad Helper Version

Latest

### Describe the bug

Gives Me An Unknown Expectation Error`

### Screenshot or screencast

![Untitled _ - VEGAS Pro 20 0 7_1_2023 2_42_05 AM](https://github.com/otomad/OtomadHelper/assets/111662331/bd8c105e-b2b4-4fe3-8726-9a173abc619d)

### Additional

Can Anyone Help Me?

**Comment by otomad** [comment]
Click "expand the details", and copy the error log to here.

**Comment by 4stacks67** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.GenerateOtomad() in c:\Users\lilzo\AppData\Local\Temp\jbrs3uab.0.cs:line 1148
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.Generate() in c:\Users\lilzo\AppData\Local\Temp\jbrs3uab.0.cs:line 2585
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.FromVegas(Vegas myVegas) in c:\Users\lilzo\AppData\Local\Temp\jbrs3uab.0.cs:line 2752

**Comment by 4stacks67** [comment]
Its on media and i tried to fix everything

**Comment by 4stacks67** [comment]
Also, everytime i add midi, i need channels, please fix this

**Comment by 4stacks67** [comment]
And theres no tuning every time i tune it

**Comment by otomad** [comment]
How do you get your midi file? Is it export by FL Studio?

**Comment by 4stacks67** [comment]
yes it wasa, and i get a channel error everytime

**Comment by otomad** [comment]
And also in the config form, have you turn off the staff visual effect?

Switch to the "Staff" tab, and uncheck the "Enable" checkbox.

**Comment by 4stacks67** [comment]
ye i did

**Comment by otomad** [comment]
> yes it wasa, and i get a channel error everytime

Can you share your midi file? Just drag that file to this comment box.

**Comment by 4stacks67** [comment]
i can't

**Comment by 4stacks67** [comment]
it wont let me

**Comment by otomad** [comment]
It seem that you can compress your midi file to a zip file, then you can upload it.

**Comment by 4stacks67** [comment]
[Fixed.zip](https://github.com/otomad/OtomadHelper/files/11924956/Fixed.zip)

**Comment by 4stacks67** [comment]
It's this, the script thinks its damage or i dont have a midi track when i do, or channels

**Comment by 4stacks67** [comment]
hello?

**Comment by otomad** [comment]
The midi you given me is empty...

**Comment by otomad** [comment]
You can simply open the midi file with Windows Media Player, and there is nothing played.

**Comment by 4stacks67** [comment]
what

**Comment by 4stacks67** [comment]
i converted it to midi wth

**Comment by 4stacks67** [comment]
hold on

**Comment by 4stacks67** [comment]
hold on

**Comment by otomad** [comment]
Have you do it in FL Studio?
> Tools > Marcos > Prepare for MIDI Export

After you do that, then you can
> File > Export > MIDI File

Or there is no notes in the midi file.

**Comment by 4stacks67** [comment]
2nd option

**Comment by 4stacks67** [comment]
File > Export > MIDI File

**Comment by otomad** [comment]
Emm, you have to do both two options.

Please look at the documentation: **9: How to do!**

![image](https://github.com/otomad/OtomadHelper/assets/56647156/bfd9c6f3-1d11-481f-b779-eeea535cc8aa)

**Comment by 4stacks67** [comment]
thx

**Comment by 4stacks67** [comment]
If it doesn't tune, i will let you know

**Comment by 4stacks67** [comment]
It wont read the file

**Comment by 4stacks67** [comment]
System.FormatException: Got an off without an on 1824 NoteOn Ch: 2 D#6 Vel:0 (Note Off)
   at NAudio.Midi.MidiFile.FindNoteOn(NoteEvent offEvent, List`1 outstandingNoteOns)
   at NAudio.Midi.MidiFile..ctor(Stream inputStream, Boolean strictChecking, Boolean ownInputStream)
   at Otomad.VegasScript.OtomadHelper.V4.MIDI..ctor(String path) in c:\Users\lilzo\AppData\Local\Temp\rgf0tyhd.0.cs:line 5311
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.OpenMidiFile(String filePath, MIDI& outMidi, Boolean inSilence) in c:\Users\lilzo\AppData\Local\Temp\rgf0tyhd.0.cs:line 349

**Comment by otomad** [comment]
#25

Your MIDI file has a note that has a velocity of 0. Check to make sure there isn't any notes that have a off value of 0 (aka notes that have no volume)

**Comment by otomad** [comment]
> If it doesn't tune, i will let you know

Emm, so why don't tune it?

**Comment by 4stacks67** [comment]
Ok ;-;

**Comment by 4stacks67** [comment]
Its already tuned but off pitch

**Comment by otomad** [comment]
> System.FormatException: Got an off without an on 1824 NoteOn Ch: 2 D#6 Vel:0 (Note Off) at NAudio.Midi.MidiFile.FindNoteOn(NoteEvent offEvent, List`1 outstandingNoteOns) at NAudio.Midi.MidiFile..ctor(Stream inputStream, Boolean strictChecking, Boolean ownInputStream) at Otomad.VegasScript.OtomadHelper.V4.MIDI..ctor(String path) in c:\Users\lilzo\AppData\Local\Temp\rgf0tyhd.0.cs:line 5311 at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.OpenMidiFile(String filePath, MIDI& outMidi, Boolean inSilence) in c:\Users\lilzo\AppData\Local\Temp\rgf0tyhd.0.cs:line 349

It seems that a bug in the NAudio library, and I am currently unable to fix it unless I rewrite a MIDI parser.

**Comment by otomad** [comment]
> Its already tuned but off pitch

Maybe NAudio thinks it as invalid MIDI, so just make it valid, and with pitch on it.

**Comment by 4stacks67** [comment]
Can you atleast make a new script for ytpmvs

**Comment by 4stacks67** [comment]
And make it as a exe file instead?

**Comment by 4stacks67** [comment]
bc i'm getting frustrated at this point

**Comment by 4stacks67** [comment]
and still doesnt work

**Comment by otomad** [comment]
Can you share your flp file? I could convert it to midi for you.

**Comment by otomad** [comment]
> And make it as a exe file instead?

I'm very sorry, my current technical capabilities are not sufficient to support this.

**Comment by 4stacks67** [comment]
> > And make it as a exe file instead?
> 
> I'm very sorry, my current technical capabilities are not sufficient to support this.

Its ok

**Comment by 4stacks67** [comment]
> Can you share your flp file? I could convert it to midi for you.

Sure

**Comment by 4stacks67** [comment]
[Medley_of_YTPMV-ver2_2.zip](https://github.com/otomad/OtomadHelper/files/11925506/Medley_of_YTPMV-ver2_2.zip)

**Comment by 4stacks67** [comment]
Here u go

**Comment by 4stacks67** [comment]
hello?

**Comment by otomad** [comment]
Oh sorry, your FL version is higher than me so I cannot open it.

![image](https://github.com/otomad/OtomadHelper/assets/56647156/0c9fb915-9759-4a78-8d48-bea85d7b1422)

**Comment by 4stacks67** [comment]
use the trial ver

**Comment by 4stacks67** [comment]
And press yes

**Comment by otomad** [comment]
However, You can follow me like this video.

https://github.com/otomad/OtomadHelper/assets/56647156/fddef15e-aaa3-40cf-84b3-e866a19ddbe8

**Comment by 4stacks67** [comment]
Its unlimited

**Comment by 4stacks67** [comment]
Also where are the velocities?

**Comment by otomad** [comment]
![image](https://github.com/otomad/OtomadHelper/assets/56647156/b644ea23-9499-41fb-aaa6-2b11abe489e0)
here

**Comment by 4stacks67** [comment]
thx
