### ISSUE TITLE
error with vegas pro 13-15: "An object of a type convertible to 'bool' is required"

### ISSUE THREAD

**Issue by bellahl** [otomad/VegasScripts#5]
been wanting to switch to vegas pro 13/14 since they're more lightweight, but it doesn't seem to work. any help is appreciated!!

![image](https://user-images.githubusercontent.com/107021526/182018872-432123f9-525f-48aa-a656-0006cd50f5f2.png)

**Comment by otomad** [comment]
The latest release should solve this problem. If you have any other questions, please reopen this issue.

**Comment by bellahl** [comment]
tested it out in 13, 14, and 15 and it now works!! thank you very much for your help

**Comment by otomad** [comment]
You're welcome. Have fun!
