### ISSUE TITLE
Picture in Picture plugin issue

### ISSUE THREAD

**Issue by sonicfan888** [otomad/VegasScripts#50]
### Vegas Pro Version

Vegas Pro 14

### Describe the bug

My VEGAS 14 says that the "Picture in Picture" plugin is not availlable and it thinks that it's not supported for my VEGAS version

### Screenshot or screencast

![bandicam 2023-07-27 11-26-11-987](https://github.com/otomad/OtomadHelper/assets/93792255/96c22242-e7b4-42e8-91df-ccaec01ce2c3)
The error.

**Comment by otomad** [comment]
What feature of Otomad Helper did you use, which required to use the Picture in Picture plugin?

Note that the Picture in Picture plugin of Vegas version less than 16 doesn't support some feature like distortion (for example, changing the height while keeping the width unchanged, transform the visual to a parallelogram).

**Comment by sonicfan888** [comment]
The Visual. When I disabled that it seemingly did nothing

**Comment by otomad** [comment]
You can try:
1. Go to "Staff" tab and uncheck "Enable" checkbox.
2. Go to "Sonar" tab and uncheck "Enable" checkbox.
3. Go to "Visual" tab, and do not use some visual effects like: Zoom Out In, Vertical Expansion, Vertical Expansion with Rebound, Vertical Compression, Vertical Compression with Rebound, Vertical Bounce, Oblique Expansion and Compression, Puyo Pop, Play Pendulum.

If you still encounter an error after trying the above steps simultaneously, please reply again.

**Comment by sonicfan888** [comment]
Worked!
Issue closed.
