### ISSUE TITLE
Always uses vegas solid color 1

### ISSUE THREAD

**Issue by 4stacks67** [otomad/VegasScripts#56]
### Vegas Pro Version

Vegas Pro 21

### Otomad Helper Version

Latest

### Describe the bug

Basically when i get a drum sample for the drum kit it always uses vegas solid color 1

**Comment by Evauation** [comment]
Sounds like #25 - I'm seeing white shapes and not the visual.

Make sure that Sonar is turned off. Sonar is automatically turned on if your MIDI detects or has a drum track/channel and is selected.

**Comment by 4stacks67** [comment]
thx
