### ISSUE TITLE
Vegas

### ISSUE THREAD

**Issue by LSHYBlire** [otomad/VegasScripts#64]
### Vegas Pro Version

Vegas Pro 20

### Otomad Helper Version

Latest

### Describe the bug

脚本可以正常生成视频，但是生成音频会报错
System.Runtime.InteropServices.COMException (0x8000FFFF): 灾难性故障 (异常来自 HRESULT:0x8000FFFF (E_UNEXPECTED))
   在 ScriptPortal.Vegas.IEventCOM.Copy(UInt32 trackID, Int64 eventID, UInt32 destTrackID, Int64 ntStart, Int64& newEventID)
   在 ScriptPortal.Vegas.TrackEvent.Copy(Track destination, Timecode startTime)
   在 Otomad.VegasScript.OtomadHelper.V4.TrackHelper`2.AddEvent[T](T trackEvent, Timecode start, Timecode length, IEnumerable`1 exceptTracks, Boolean isSampleEvent) 位置 c:\Users\DELL\AppData\Local\Temp\yozgvcjk.0.cs:行号 11166
   在 Otomad.VegasScript.OtomadHelper.V4.EntryPoint.GenerateOtomad() 位置 c:\Users\DELL\AppData\Local\Temp\yozgvcjk.0.cs:行号 1239
   在 Otomad.VegasScript.OtomadHelper.V4.EntryPoint.Generate() 位置 c:\Users\DELL\AppData\Local\Temp\yozgvcjk.0.cs:行号 2605
   在 Otomad.VegasScript.OtomadHelper.V4.EntryPoint.FromVegas(Vegas myVegas) 位置 c:\Users\DELL\AppData\Local\Temp\yozgvcjk.0.cs:行号 2773

![屏幕截图 2024-02-07 024851](https://github.com/otomad/OtomadHelper/assets/159183836/4770a193-1fa5-47ed-9df6-a0cfe8b59213)
在之后的操作里经常会大量弹出“处理重做缓冲区时发生错误”的窗口，关掉后会继续出现10次左右
![屏幕截图 2024-02-07 025129](https://github.com/otomad/OtomadHelper/assets/159183836/a48e6111-e4df-4099-9d23-cc1314496d4c)
这种情况要怎么处理

**Comment by Evauation** [comment]
@otomad

**Comment by otomad** [comment]
看起来像是复制剪辑时出现了问题。

您可以尝试下：

1. 在脚本对话框中，点击左上角文件→重置用户配置，看看是否是配置方面出现了问题。

2. 检查一下其它 MIDI 文件是否出现了同样的问题，如果没有，可以提供一下你的 MIDI 看看是否是 MIDI 方面出现了问题。
