### ISSUE TITLE
vegas pro 20 crashes when generating video using a clip that has video effects applied

### ISSUE THREAD

**Issue by MikaelSunflowerseed** [otomad/VegasScripts#70]
### Vegas Pro Version

Vegas Pro 20

### Otomad Helper Version

Latest

### Describe the bug

when trying to generate video with a video effect,the software crashes

### Screenshot or screencast

![Screenshot (237)](https://github.com/otomad/OtomadHelper/assets/155904622/f2e5d9dd-3576-4a46-aec0-c47cdb0cdc6e)

**Comment by MikaelSunflowerseed** [comment]
![Screenshot (238)](https://github.com/otomad/OtomadHelper/assets/155904622/926f61db-2b12-4245-b6a7-6b8dc0d68517)
additional screenshot

**Comment by Evauation** [comment]
What were the video effects in question? Is the MIDI at fault? Have you tried generating the visuals without effects in the clips first?

**Comment by MikaelSunflowerseed** [comment]
> What were the video effects in question? Is the MIDI at fault? Have you tried generating the visuals without effects in the clips first?

the effect was "crop",i have tried making one without the effect and it worked well

**Comment by otomad** [comment]
I am using VEGAS Pro 20 and a clip with "Crop" effects too, but it works fine and doesn't crash.

Can you click "Show problem details" checkbox in the VEGAS crash dialog and show me the details?

**Comment by Evauation** [comment]
stale issue
