### ISSUE TITLE
VEGAS Pro 22 build 122 的不兼容性及临时解决办法

### ISSUE THREAD

**Issue by zzzzzz9125** [otomad/VegasScripts#79]
### Vegas Pro Version

Vegas Pro 22

### Otomad Helper Version

Latest

### Describe the bug

VEGAS Pro 22 build 122 使用 Otomad Helper 时会如下报错：![image](https://github.com/user-attachments/assets/a80b68c6-02f9-4b56-bc63-88d9400fe594)
问题在于 Magix 暗改了脚本 API，把原先的 `Vegas.ImportFile(string fileName, bool mediaPoolOnly)` 改成了 `Vegas.ImportFile(string fileName, bool mediaPoolOnly, bool enablePromptMatchFirstVideo)`。也就是说， `Vegas.ImportFile()` 现在只支持 1 或 3 个参数，而不支持原先的 2 个参数的写法。
脚本要改也比较容易，但会破坏对旧版的兼容性，因此只是临时的办法：将脚本内的 `vegas.ImportFile(clipName, true);` 全部替换成 `vegas.ImportFile(clipName, true, false);` 即可。
该兼容性问题已在 VEGAS 论坛中提出，需等待新版修复：https://www.vegascreativesoftware.info/us/forum/bug-vegas-importfile-no-longer-works-the-way-it-used-to-in-22-b122--147357/

**Comment by otomad** [comment]
别急，我马上推出一个v4.x的最终版本，其中将会修复包括这个在内的不少错误，然后将停止v4.x的更新。全力投入下一个版本的更新。

**Comment by Evauation** [comment]
Awesome!
