### ISSUE TITLE
"Message Missing" Error

### ISSUE THREAD

**Issue by WeatherMarioBrosYT** [otomad/VegasScripts#82]
### Vegas Pro Version

Vegas Pro 18

### Otomad Helper Version

Latest

### Describe the bug

I have been experiencing this error many times and I am gonna decide to talk about it now. I have been using Vegas Pro 18 for a year now and I have decided to download the Otomad Helper today. And for some reason, I keep getting errors for "message missing" with the error code 0x80131600. And when I took a look at the file, the CS file for it doesn't pop up. I knew this cause instead of the paper icon on the otomad helper thing like the other scripts, it has some random cyan circle icon. Meaning for some reason, it only detects the icon and not the CS file for it itself. And when I went to run script and clicked on the CS file itself, I got the same error code or sometimes it would just say "not responding". Does anyone know how to fix it?

### Logs

Error 1:

An error occurred during execution of the script C:\Users\DJ\Downloads\VEGAS Pro 18.0-20230730T1928397-001\VEGAS Pro 18.0\Script Menu\OtomadHelper-winform\OtomadHelper-winform\otomad_helper\Otomad Helper.cs.

Error 0x80131600 (message missing)

Error 2:

VEGAS Pro 18.0
An error occurred during execution of the script.
Error 0x80131600 (message missing)

Details:
C:\Users\DJ\Downloads\VEGAS Pro 18.0-20230730T192839Z-001\VEGAS Pro 18.0\Script Menu\OtomadHelper-
winform\otomad_helper\Otomad Helper.cs: Metadata file 'C:\Users\DJ\Downloads\VEGAS Pro 18.0-
20230730T192839Z-001\VEGAS Pro 18.0\Script Menu\OtomadHelper-winform\otomad_helper\DLL\NAudio.dll' could not be found

### Screenshot or screencast

Here are the screenshots for more understandable context.
![Screenshot 2024-10-28 155819](https://github.com/user-attachments/assets/07c4c61c-5d98-472d-829a-0f9499a92027)
![Screenshot 2024-10-28 155426](https://github.com/user-attachments/assets/54633fc4-44cd-4f5f-9d30-2fe8d7cc6480)
![Screenshot 2024-10-28 155355](https://github.com/user-attachments/assets/c2f17fc3-2454-4aa8-9bf9-373d23e1e9d9)

**Comment by Evauation** [comment]
#25

> Otomad Helper doesn't work when I run it.
> 
> Make sure you have the latest and corresponding version for the Vegas Pro version you have. 13, 14+, and 16+ each have their own different version. Download the version that matches your Vegas Pro version. You also need NAudio installed alongside it, which comes with the script, this is required. Make sure NAudio has its respective folder in the script menu folder.

Surely you have the NAudio DLL in the DLL folder which should be next to the CS script and the NAudio DLL should be unblocked. Check by right clicking the DLL and see if it’s blocked. If it is, unblock it and try again.

also it showing an icon instead of the paper icon is because Otomad Helper has a display icon for the script, it’s purely cosmetic.

**Comment by Demiomad** [comment]
Same error happened.

**Comment by Demiomad** [comment]
> #25
> 
> > Otomad Helper doesn't work when I run it.
> > Make sure you have the latest and corresponding version for the Vegas Pro version you have. 13, 14+, and 16+ each have their own different version. Download the version that matches your Vegas Pro version. You also need NAudio installed alongside it, which comes with the script, this is required. Make sure NAudio has its respective folder in the script menu folder.
> 
> Surely you have the NAudio DLL in the DLL folder which should be next to the CS script and the NAudio DLL should be unblocked. Check by right clicking the DLL and see if it’s blocked. If it is, unblock it and try again.
> 
> also it showing an icon instead of the paper icon is because Otomad Helper has a display icon for the script, it’s purely cosmetic.

What do you mean "unblock"?
How do I unblock it?

**Comment by Evauation** [comment]
![image](https://github.com/user-attachments/assets/09af4466-53c5-4b10-a6f2-292f02d99e37)
This is how you would unblock the DLL if this is causing any issues.
Right click to properties -> unblock -> apply

However if your computer has trusted the DLL, it won't show this option.

**Comment by Evauation** [comment]
> ### Vegas Pro Version
> 
> Vegas Pro 18
> ### Otomad Helper Version
> 
> Latest
> ### Describe the bug
> 
> I have been experiencing this error many times and I am gonna decide to talk about it now. I have been using Vegas Pro 18 for a year now and I have decided to download the Otomad Helper today. And for some reason, I keep getting errors for "message missing" with the error code 0x80131600. And when I took a look at the file, the CS file for it doesn't pop up. I knew this cause instead of the paper icon on the otomad helper thing like the other scripts, it has some random cyan circle icon. Meaning for some reason, it only detects the icon and not the CS file for it itself. And when I went to run script and clicked on the CS file itself, I got the same error code or sometimes it would just say "not responding". Does anyone know how to fix it?
> ### Logs
> 
> Error 1:
> 
> An error occurred during execution of the script C:\Users\DJ\Downloads\VEGAS Pro 18.0-20230730T1928397-001\VEGAS Pro 18.0\Script Menu\OtomadHelper-winform\OtomadHelper-winform\otomad_helper\Otomad Helper.cs.
> 
> Error 0x80131600 (message missing)
> 
> Error 2:
> 
> VEGAS Pro 18.0 An error occurred during execution of the script. Error 0x80131600 (message missing)
> 
> Details: C:\Users\DJ\Downloads\VEGAS Pro 18.0-20230730T192839Z-001\VEGAS Pro 18.0\Script Menu\OtomadHelper- winform\otomad_helper\Otomad Helper.cs: Metadata file 'C:\Users\DJ\Downloads\VEGAS Pro 18.0- 20230730T192839Z-001\VEGAS Pro 18.0\Script Menu\OtomadHelper-winform\otomad_helper\DLL\NAudio.dll' could not be found
> ### Screenshot or screencast
> 
> Here are the screenshots for more understandable context. ![Screenshot 2024-10-28 155819](https://private-user-images.githubusercontent.com/186633214/380873913-07c4c61c-5d98-472d-829a-0f9499a92027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODkxOTYsIm5iZiI6MTczMDM4ODg5NiwicGF0aCI6Ii8xODY2MzMyMTQvMzgwODczOTEzLTA3YzRjNjFjLTVkOTgtNDcyZC04MjlhLTBmOTQ5OWE5MjAyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNTM0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjA1ZmM0NjFmMTQwMGJmYmQzMmFlOTM2MTg1ODM2OTFkZWY5ZTk5ZWFiNzQxZjA0M2E4ZmQ3NTM3ZDdmMDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0jcNQpIwY4gKSWFgoJ154WgIMc76jgwhFZPKfEqPrnI) ![Screenshot 2024-10-28 155426](https://private-user-images.githubusercontent.com/186633214/380873922-54633fc4-44cd-4f5f-9d30-2fe8d7cc6480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODkxOTYsIm5iZiI6MTczMDM4ODg5NiwicGF0aCI6Ii8xODY2MzMyMTQvMzgwODczOTIyLTU0NjMzZmM0LTQ0Y2QtNGY1Zi05ZDMwLTJmZThkN2NjNjQ4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNTM0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGNjNmZiMmFhYmM3ODRiNTIwYzk2MzQ2YmNkNWM3NTAyODU5NWQ3MmViYjUxZDY3YmQ3ZGI2YjBjYjJlYjAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iEfuUU6m4p8YGSc5two6bI0XarBcsBE_chiPXCF6rM4) ![Screenshot 2024-10-28 155355](https://private-user-images.githubusercontent.com/186633214/380873926-c2f17fc3-2454-4aa8-9bf9-373d23e1e9d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODkxOTYsIm5iZiI6MTczMDM4ODg5NiwicGF0aCI6Ii8xODY2MzMyMTQvMzgwODczOTI2LWMyZjE3ZmMzLTI0NTQtNGFhOC05YmY5LTM3M2QyM2UxZTlkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNTM0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Yjg3YTQ4NWYyYTJhODBmZjg4ZjlkYTY4OWRmNTNmMjk2NjYxMGVlZDNlMGQ1MmVjNWM4NjlmNjgxZjI4OGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SxqTTAp5JijU9hSRi4tgGk5SN5acrIXubhPGZix0wjg)
> ### Additional
> 
> _No response_

### Wait a minute, I didn't notice till now you downloaded the source code instead of the actual script for Vegas Pro

### Grab the latest release for your corresponding Vegas Pro version and place that in your script menu!

# https://github.com/otomad/OtomadHelper/releases/latest

**Comment by otomad** [comment]
> ### Wait a minute, I didn't notice till now you downloaded the source code instead of the actual script for Vegas Pro
> 
> ### Grab the latest release for your corresponding Vegas Pro version and place that in your script menu!
> 
> # https://github.com/otomad/OtomadHelper/releases/latest

I wonder why there are so many people download the source codes instead of the released distribution.

**Comment by Demiomad** [comment]
> ![image](https://private-user-images.githubusercontent.com/108847709/382007093-09af4466-53c5-4b10-a6f2-292f02d99e37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NjE3NTEsIm5iZiI6MTczMDQ2MTQ1MSwicGF0aCI6Ii8xMDg4NDc3MDkvMzgyMDA3MDkzLTA5YWY0NDY2LTUzYzUtNGIxMC1hNmYyLTI5MmYwMmQ5OWUzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxMTQ0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGY1OTI1MzlhYzQ3NmU1YjI5YzJhODhmNzU0ZmM2NjQ5NGIzZTczMjNhYzk2NjFkZjc2NjhkYWEyYmI4ODNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7l__MpEsGKEeJabqttc-jgCL810LzgZpwBYOlQPrD5o) This is how you would unblock the DLL if this is causing any issues. Right click to properties -> unblock -> apply
> 
> However if your computer has trusted the DLL, it won't show this option.

I am in fact, on Windows 11 and Windows trusted the DLL.

**Comment by Demiomad** [comment]
Oh and, I'm on VEGAS Pro 22.0

**Comment by otomad** [comment]
> Oh and, I'm on VEGAS Pro 22.0

Download the Vegas Pro 22 version of the script, at the link:
https://github.com/otomad/OtomadHelper/releases/latest

And click the link with this name below:
0_otomad_helper_vx.xx.x.x_vegas22.zip

**Comment by Demiomad** [comment]
I have the DLL.

I have a different problem.

C:\Program Files\VEGAS\VEGAS Pro 22.0\Script Menu\Otomad Helper.cs(382) : No overload for method 'ImportFile' takes 3 arguments
C:\Program Files\VEGAS\VEGAS Pro 22.0\Script Menu\Otomad Helper.cs(407) : No overload for method 'ImportFile' takes 3 arguments

**Comment by Demiomad** [comment]
> Same error happened.

I meant similar error.

**Comment by otomad** [comment]
> I have the DLL.
> 
> I have a different problem.
> 
> C:\Program Files\VEGAS\VEGAS Pro 22.0\Script Menu\Otomad Helper.cs(382) : No overload for method 'ImportFile' takes 3 arguments
> C:\Program Files\VEGAS\VEGAS Pro 22.0\Script Menu\Otomad Helper.cs(407) : No overload for method 'ImportFile' takes 3 arguments
> 

~~You have downloaded the script for Vegas Pro 16~21 versions only, please download the script for Vegas Pro 22 version.~~

What's your Vegas Pro full version? 22.0.0.122?

**Comment by Demiomad** [comment]
VEGAS Pro 22.0 (Build 93)

**Comment by Demiomad** [comment]
so maybe 22.0.0.93 or something

**Comment by PolishBoiYT** [comment]
I'll update my VEGAS,

**Comment by otomad** [comment]
> so maybe 22.0.0.93 or something

Maybe you can try the script for Vegas Pro 16 ~ 21 versions. I guess the API changed after build 122.

**Comment by otomad** [comment]
@PolishBoiYT The lastest version may solve your problem.

https://github.com/otomad/OtomadHelper/releases/latest

**Comment by Demiomad** [comment]
Thank you! That worked!

I could use the 16 - 21 versions but I may miss new features.

**Comment by otomad** [comment]
> Thank you! That worked!
> 
> I could use the 16 - 21 versions but I may miss new features.

Please check out the lastest release, which merged script for 16 - 21 versions and the 22 version.
